#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         3
bspc config window_gap           9
bspc config focused_border_color "#a89984"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a kitty desktop='^2' follow=on focus=on
bspc rule -a firefox desktop='^1' follow=on focus=on
bspc rule -a Google-chrome desktop='^1' follow=on focus=on
bspc rule -a Code desktop='^3' follow=on focus=on
bspc rule -a spotify desktop='^4' follow=on focus=on
bspc rule -a Screenkey manage=off

setxkbmap -option caps:escape

picom -b &

nitrogen --restore &

ibus-daemon -d

xsetroot -cursor_name left_ptr &

$HOME/.config/polybar/launch.sh &


