#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty desktop='^2' follow=on focus=on
bspc rule -a Google-chrome desktop='^1' follow=on focus=on
bspc rule -a Code desktop='^3' follow=on focus=on
bspc rule -a Spotify desktop='^4' follow=on focus=on
bspc rule -a Screenkey manage=off

picom -b &

nitrogen --restore &

$HOME/.config/polybar/launch.sh &

xsetroot -cursor_name left_ptr &


